const { buildCountryPath } = require('../../libs/commerce.js');

module.exports = {
  name: 'Commerce',
  features: [
    {
      tcid: '0',
      name: '@Commerce-WCS-Country-Locale',
      // Default path builder: uses basePath with country prefix
      pathBuilder: buildCountryPath,
      // Environments to test (defaults to ['prod'] if not specified, or uses COMMERCE_ENV if set)
      envs: ['stage'], // Can be ['prod'], ['stage'], or ['prod', 'stage']
      paths: [
        // {
        //   path: '/drafts/nala/features/commerce/commerce-loc',
        //   expectedServer: true, // change to "true" for checking new wcs server
        // },
        {
          path: '/creativecloud/plans.html',
          baseURL: 'https://www.adobe.com', // Override framework baseURL for this path
          skipCountries: ['US', 'MT', 'CY', 'CN', 'RU', 'NO'], // Skip US locale for this path
          expectedServer: true, // change to "true" for checking new wcs server
          skipElementCheck: true, // Skip waiting for commerce elements to be visible
        },
      ],
      data: {
        countries: [
          { country: 'AE', locale: 'en_AE', urlPrefix: 'ae_en' },
          { country: 'AE', locale: 'ar_AE', urlPrefix: 'ae_ar' },
          { country: 'AR', locale: 'es_AR' },
          { country: 'AT', locale: 'de_AT' },
          { country: 'AU', locale: 'en_AU' },
          { country: 'BE', locale: 'en_BE', urlPrefix: 'be_en' },
          { country: 'BE', locale: 'fr_BE', urlPrefix: 'be_fr' },
          { country: 'BE', locale: 'nl_BE', urlPrefix: 'be_nl' },
          { country: 'BG', locale: 'bg_BG' },
          { country: 'BR', locale: 'pt_BR' },
          { country: 'CA', locale: 'en_CA' },
          { country: 'CA', locale: 'fr_CA', urlPrefix: 'ca_fr' },
          { country: 'CH', locale: 'de_CH', urlPrefix: 'ch_de' },
          { country: 'CH', locale: 'fr_CH', urlPrefix: 'ch_fr' },
          { country: 'CH', locale: 'it_CH', urlPrefix: 'ch_it' },
          { country: 'CL', locale: 'es_CL' },
          { country: 'CN', locale: 'zh-hans_CN' },
          { country: 'CO', locale: 'es_CO' },
          { country: 'CR', locale: 'es_CR' },
          { country: 'CY', locale: 'en_CY', urlPrefix: 'cy_en' },
          { country: 'CZ', locale: 'cs_CZ' },
          { country: 'DE', locale: 'de_DE' },
          { country: 'DK', locale: 'da_DK' },
          { country: 'DO', locale: 'es_DO', urlPrefix: 'la' },
          { country: 'DZ', locale: 'en_DZ', urlPrefix: 'mena_en' },
          { country: 'DZ', locale: 'ar_DZ', urlPrefix: 'mena_ar' },
          { country: 'EC', locale: 'es_EC' },
          { country: 'EE', locale: 'et_EE' },
          { country: 'EG', locale: 'en_EG', urlPrefix: 'eg_en' },
          { country: 'EG', locale: 'ar_EG', urlPrefix: 'eg_ar' },
          { country: 'ES', locale: 'es_ES' },
          { country: 'FI', locale: 'fi_FI' },
          { country: 'FR', locale: 'fr_FR' },
          { country: 'GB', locale: 'en_GB', urlPrefix: 'uk' },
          { country: 'GR', locale: 'el_GR', urlPrefix: 'gr_el' },
          { country: 'GR', locale: 'en_GR', urlPrefix: 'gr_en' },
          { country: 'GT', locale: 'es_GT' },
          { country: 'HK', locale: 'en_HK', urlPrefix: 'hk_en' },
          { country: 'HK', locale: 'zh-hant_HK', urlPrefix: 'hk_zh' },
          { country: 'HU', locale: 'hu_HU' },
          { country: 'ID', locale: 'en_ID', urlPrefix: 'id_en' },
          { country: 'ID', locale: 'id_ID', urlPrefix: 'id_id' },
          { country: 'IE', locale: 'en_IE' },
          { country: 'IL', locale: 'iw_IL', urlPrefix: 'il_he' },
          { country: 'IL', locale: 'en_IL', urlPrefix: 'il_en' },
          { country: 'IN', locale: 'en_IN' },
          { country: 'IN', locale: 'hi_IN', urlPrefix: 'in_hi' },
          { country: 'IT', locale: 'it_IT' },
          { country: 'JP', locale: 'ja_JP' },
          { country: 'KR', locale: 'ko_KR' },
          { country: 'KW', locale: 'en_KW', urlPrefix: 'kw_en' },
          { country: 'KW', locale: 'ar_KW', urlPrefix: 'kw_ar' },
          { country: 'LT', locale: 'lt_LT' },
          { country: 'LU', locale: 'en_LU', urlPrefix: 'lu_en' },
          { country: 'LU', locale: 'fr_LU', urlPrefix: 'lu_fr' },
          { country: 'LU', locale: 'de_LU', urlPrefix: 'lu_de' },
          { country: 'LV', locale: 'lv_LV' },
          { country: 'MT', locale: 'en_MT' },
          { country: 'MU', locale: 'en_MU', urlPrefix: 'africa' },
          { country: 'MX', locale: 'es_MX' },
          { country: 'MY', locale: 'en_MY', urlPrefix: 'my_en' },
          { country: 'MY', locale: 'ms_MY', urlPrefix: 'my_ms' },
          { country: 'NG', locale: 'en_NG' },
          { country: 'NL', locale: 'nl_NL' },
          { country: 'NO', locale: 'nb_NO' },
          { country: 'NZ', locale: 'en_NZ' },
          { country: 'PE', locale: 'es_PE' },
          { country: 'PH', locale: 'en_PH', urlPrefix: 'ph_en' },
          { country: 'PH', locale: 'fil_PH', urlPrefix: 'ph_fil' },
          { country: 'PL', locale: 'pl_PL' },
          { country: 'PT', locale: 'pt_PT' },
          { country: 'QA', locale: 'en_QA', urlPrefix: 'qa_en' },
          { country: 'QA', locale: 'ar_QA', urlPrefix: 'qa_ar' },
          { country: 'RO', locale: 'ro_RO' },
          { country: 'RU', locale: 'ru_RU' },
          { country: 'SA', locale: 'en_SA', urlPrefix: 'sa_en' },
          { country: 'SA', locale: 'ar_SA', urlPrefix: 'sa_ar' },
          { country: 'SE', locale: 'sv_SE' },
          { country: 'SG', locale: 'en_SG' },
          { country: 'SI', locale: 'sl_SI' },
          { country: 'SK', locale: 'sk_SK' },
          { country: 'TH', locale: 'en_TH', urlPrefix: 'th_en' },
          { country: 'TH', locale: 'th_TH', urlPrefix: 'th_th' },
          { country: 'TM', locale: 'en_TM', urlPrefix: 'cis_en' },
          { country: 'TM', locale: 'ru_TM', urlPrefix: 'cis_ru' },
          { country: 'TR', locale: 'tr_TR' },
          { country: 'TW', locale: 'zh-hant_TW' },
          { country: 'UA', locale: 'uk_UA' },
          { country: 'US', locale: 'en_US' },
          { country: 'US', locale: 'en_US', urlPrefix: 'pr' },
          { country: 'VN', locale: 'en_VN', urlPrefix: 'vn_en' },
          { country: 'VN', locale: 'vi_VN', urlPrefix: 'vn_vi' },
          { country: 'ZA', locale: 'en_ZA' },
        ],
      },
      tags: '@commerce @smoke @regression',
    },
    {
      tcid: '1',
      name: '@Commerce-WCS-Geo-Country-Locale',
      // Environments to test (defaults to ['prod'] if not specified, or uses COMMERCE_ENV if set)
      envs: ['stage'], // Can be ['prod'], ['stage'], or ['prod', 'stage']
      paths: [
        {
          path: '/drafts/nala/features/commerce/commerce-loc-geo',
          expectedLocale: (akamaiLocale, type) => (type === 'supported' ? `en_${akamaiLocale}` : 'en_US'),
          expectedServer: true, // change to "true" for checking new wcs server
        },
        {
          path: '/fr/drafts/nala/features/commerce/commerce-loc-geo',
          expectedLocale: (akamaiLocale, type) => (type === 'supported' ? `fr_${akamaiLocale}` : 'fr_US'),
          expectedServer: true, // change to "true" for checking new wcs server
        },
      ],
      data: {
        akamaiLocales: {
          supported: ['AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BR', 'CA', 'CH', 'CL', 'CN', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HU', 'ID', 'IE', 'IL', 'IN', 'IT', 'JP', 'KR', 'KW', 'LT', 'LU', 'LV', 'MT', 'MU', 'MX', 'MY', 'NG', 'NL', 'NO', 'NZ', 'PE', 'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'SA', 'SE', 'SG', 'SI', 'SK', 'TH', 'TM', 'TR', 'TW', 'UA', 'US', 'VN', 'ZA', 'AM', 'AZ', 'BB', 'BD', 'BH', 'BO', 'BS', 'BY', 'GE', 'GH', 'HN', 'HR', 'IQ', 'IS', 'JM', 'JO', 'KE', 'KG', 'KZ', 'LB', 'LK', 'MA', 'MD', 'MO', 'NI', 'NP', 'OM', 'PA', 'PK', 'PY', 'RS', 'SV', 'TJ', 'TN', 'TT', 'TZ', 'UY', 'UZ', 'VE', 'YE'],
          // 'non-supported': ['NA', 'MM', 'SL', 'ML', 'ET', 'BF'],
          'non-supported': ['US'],
        },
      },
      browserParams: '?akamaiLocale=',
      tags: '@commerce @smoke @regression',
    },
    {
      tcid: '2',
      name: '@Commerce-MAS-Geo-Country-Locale',
      // Environments to test (defaults to ['prod'] if not specified, or uses COMMERCE_ENV if set)
      envs: ['prod'], // Can be ['prod'], ['stage'], or ['prod', 'stage']
      paths: [
        {
          path: '/drafts/nala/features/commerce/plans2',
          expectedLocale: 'en_US',
        },
      ],
      data: {
        akamaiLocales: ['AE', 'AR', 'AT', 'AU', 'BE', 'BG', 'BR', 'CA', 'CH', 'CL', 'CN', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FR', 'GB', 'GR', 'GT', 'HK', 'HU', 'ID', 'IE', 'IL', 'IN', 'IT', 'JP', 'KR', 'KW', 'LT', 'LU', 'LV', 'MT', 'MU', 'MX', 'MY', 'NG', 'NL', 'NO', 'NZ', 'PE', 'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'SA', 'SE', 'SG', 'SI', 'SK', 'TH', 'TM', 'TR', 'TW', 'UA', 'US', 'VN', 'ZA', 'AM', 'AZ', 'BB', 'BD', 'BH', 'BO', 'BS', 'BY', 'GE', 'GH', 'HN', 'HR', 'IQ', 'IS', 'JM', 'JO', 'KE', 'KG', 'KZ', 'LB', 'LK', 'MA', 'MD', 'MO', 'NI', 'NP', 'OM', 'PA', 'PK', 'PY', 'RS', 'SV', 'TJ', 'TN', 'TT', 'TZ', 'UY', 'UZ', 'VE', 'YE'],
      },
      browserParams: '?akamaiLocale=',
      tags: '@commerce @smoke @regression',
    },
    {
      tcid: '3',
      name: '@Commerce-Tax-Labels-Defaults',
      // Use the same pathBuilder as feature[0]
      pathBuilder: buildCountryPath,
      path: '/drafts/mili/tax-label-test',
      data: {
        countries: [
          { country: 'AE', locale: 'en_AE', urlPrefix: 'ae_en' },
          { country: 'AE', locale: 'ar_AE', urlPrefix: 'ae_ar' },
          { country: 'AR', locale: 'es_AR' },
          { country: 'AT', locale: 'de_AT' },
          { country: 'AU', locale: 'en_AU' },
          { country: 'BE', locale: 'en_BE', urlPrefix: 'be_en' },
          { country: 'BE', locale: 'fr_BE', urlPrefix: 'be_fr' },
          { country: 'BE', locale: 'nl_BE', urlPrefix: 'be_nl' },
          { country: 'BG', locale: 'bg_BG' },
          { country: 'BR', locale: 'pt_BR' },
          { country: 'CA', locale: 'en_CA' },
          { country: 'CA', locale: 'fr_CA', urlPrefix: 'ca_fr' },
          { country: 'CH', locale: 'de_CH', urlPrefix: 'ch_de' },
          { country: 'CH', locale: 'fr_CH', urlPrefix: 'ch_fr' },
          { country: 'CH', locale: 'it_CH', urlPrefix: 'ch_it' },
          { country: 'CL', locale: 'es_CL' },
          { country: 'CO', locale: 'es_CO' },
          { country: 'CR', locale: 'es_CR' },
          { country: 'CY', locale: 'en_CY', urlPrefix: 'cy_en' },
          { country: 'CZ', locale: 'cs_CZ' },
          { country: 'DE', locale: 'de_DE' },
          { country: 'DK', locale: 'da_DK' },
          { country: 'DO', locale: 'es_DO', urlPrefix: 'la' },
          { country: 'DZ', locale: 'en_DZ', urlPrefix: 'mena_en' },
          { country: 'DZ', locale: 'ar_DZ', urlPrefix: 'mena_ar' },
          { country: 'EC', locale: 'es_EC' },
          { country: 'EE', locale: 'et_EE' },
          { country: 'EG', locale: 'en_EG', urlPrefix: 'eg_en' },
          { country: 'EG', locale: 'ar_EG', urlPrefix: 'eg_ar' },
          { country: 'ES', locale: 'es_ES' },
          { country: 'FI', locale: 'fi_FI' },
          { country: 'FR', locale: 'fr_FR' },
          { country: 'GB', locale: 'en_GB', urlPrefix: 'uk' },
          { country: 'GR', locale: 'el_GR', urlPrefix: 'gr_el' },
          { country: 'GR', locale: 'en_GR', urlPrefix: 'gr_en' },
          { country: 'GT', locale: 'es_GT' },
          { country: 'HK', locale: 'en_HK', urlPrefix: 'hk_en' },
          { country: 'HK', locale: 'zh-hant_HK', urlPrefix: 'hk_zh' },
          { country: 'HU', locale: 'hu_HU' },
          { country: 'ID', locale: 'en_ID', urlPrefix: 'id_en' },
          { country: 'ID', locale: 'id_ID', urlPrefix: 'id_id' },
          { country: 'IE', locale: 'en_IE' },
          { country: 'IL', locale: 'iw_IL', urlPrefix: 'il_he' },
          { country: 'IL', locale: 'en_IL', urlPrefix: 'il_en' },
          { country: 'IN', locale: 'en_IN' },
          { country: 'IN', locale: 'hi_IN', urlPrefix: 'in_hi' },
          { country: 'IT', locale: 'it_IT' },
          { country: 'JP', locale: 'ja_JP' },
          { country: 'KR', locale: 'ko_KR' },
          { country: 'KW', locale: 'en_KW', urlPrefix: 'kw_en' },
          { country: 'KW', locale: 'ar_KW', urlPrefix: 'kw_ar' },
          { country: 'LT', locale: 'lt_LT' },
          { country: 'LU', locale: 'en_LU', urlPrefix: 'lu_en' },
          { country: 'LU', locale: 'fr_LU', urlPrefix: 'lu_fr' },
          { country: 'LU', locale: 'de_LU', urlPrefix: 'lu_de' },
          { country: 'LV', locale: 'lv_LV' },
          { country: 'MT', locale: 'en_MT' },
          { country: 'MU', locale: 'en_MU', urlPrefix: 'africa' },
          { country: 'MX', locale: 'es_MX' },
          { country: 'MY', locale: 'en_MY', urlPrefix: 'my_en' },
          { country: 'MY', locale: 'ms_MY', urlPrefix: 'my_ms' },
          { country: 'NG', locale: 'en_NG' },
          { country: 'NL', locale: 'nl_NL' },
          { country: 'NO', locale: 'nb_NO' },
          { country: 'NZ', locale: 'en_NZ' },
          { country: 'PE', locale: 'es_PE' },
          { country: 'PH', locale: 'en_PH', urlPrefix: 'ph_en' },
          { country: 'PH', locale: 'fil_PH', urlPrefix: 'ph_fil' },
          { country: 'PL', locale: 'pl_PL' },
          { country: 'PT', locale: 'pt_PT' },
          { country: 'QA', locale: 'en_QA', urlPrefix: 'qa_en' },
          { country: 'QA', locale: 'ar_QA', urlPrefix: 'qa_ar' },
          { country: 'RO', locale: 'ro_RO' },
          { country: 'RU', locale: 'ru_RU' },
          { country: 'SA', locale: 'en_SA', urlPrefix: 'sa_en' },
          { country: 'SA', locale: 'ar_SA', urlPrefix: 'sa_ar' },
          { country: 'SE', locale: 'sv_SE' },
          { country: 'SG', locale: 'en_SG' },
          { country: 'SI', locale: 'sl_SI' },
          { country: 'SK', locale: 'sk_SK' },
          { country: 'TH', locale: 'en_TH', urlPrefix: 'th_en' },
          { country: 'TH', locale: 'th_TH', urlPrefix: 'th_th' },
          { country: 'TM', locale: 'en_TM', urlPrefix: 'cis_en' },
          { country: 'TM', locale: 'ru_TM', urlPrefix: 'cis_ru' },
          { country: 'TR', locale: 'tr_TR' },
          { country: 'TW', locale: 'zh-hant_TW' },
          { country: 'UA', locale: 'uk_UA' },
          { country: 'US', locale: 'en_US' },
          { country: 'US', locale: 'en_US', urlPrefix: 'pr' },
          { country: 'VN', locale: 'en_VN', urlPrefix: 'vn_en' },
          { country: 'VN', locale: 'vi_VN', urlPrefix: 'vn_vi' },
          { country: 'ZA', locale: 'en_ZA' },
        ],
      },
      tags: '@commerce @smoke @regression',
    },
  ],
};
